//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLanguages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLLanguages.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンバート.
        /// </summary>
        public static string Button_Convert {
            get {
                return ResourceManager.GetString("Button_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロード.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルフォーマット.
        /// </summary>
        public static string Button_Format {
            get {
                return ResourceManager.GetString("Button_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メタデータ.
        /// </summary>
        public static string Button_Metadata {
            get {
                return ResourceManager.GetString("Button_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを開く.
        /// </summary>
        public static string Button_OpenFile {
            get {
                return ResourceManager.GetString("Button_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダ開ける.
        /// </summary>
        public static string Button_OpenFolder {
            get {
                return ResourceManager.GetString("Button_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3gp.
        /// </summary>
        public static string Formats_3gp {
            get {
                return ResourceManager.GetString("Formats_3gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flv.
        /// </summary>
        public static string Formats_flv {
            get {
                return ResourceManager.GetString("Formats_flv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m4a.
        /// </summary>
        public static string Formats_m4a {
            get {
                return ResourceManager.GetString("Formats_m4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkv.
        /// </summary>
        public static string Formats_mkv {
            get {
                return ResourceManager.GetString("Formats_mkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        public static string Formats_mp3 {
            get {
                return ResourceManager.GetString("Formats_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp4.
        /// </summary>
        public static string Formats_mp4 {
            get {
                return ResourceManager.GetString("Formats_mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webm.
        /// </summary>
        public static string Formats_webm {
            get {
                return ResourceManager.GetString("Formats_webm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        public static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォーマット.
        /// </summary>
        public static string Label_Format {
            get {
                return ResourceManager.GetString("Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リンク.
        /// </summary>
        public static string Label_Link {
            get {
                return ResourceManager.GetString("Label_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードタイプ.
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Audio.
        /// </summary>
        public static string OpenFolder_Audio {
            get {
                return ResourceManager.GetString("OpenFolder_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Converted.
        /// </summary>
        public static string OpenFolder_Convert {
            get {
                return ResourceManager.GetString("OpenFolder_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted.
        /// </summary>
        public static string OpenFolder_Formatted {
            get {
                return ResourceManager.GetString("OpenFolder_Formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string OpenFolder_Logs {
            get {
                return ResourceManager.GetString("OpenFolder_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video.
        /// </summary>
        public static string OpenFolder_Video {
            get {
                return ResourceManager.GetString("OpenFolder_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        public static string Placeholder_File {
            get {
                return ResourceManager.GetString("Placeholder_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Link.
        /// </summary>
        public static string Placeholder_Link {
            get {
                return ResourceManager.GetString("Placeholder_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string Placeholder_Optional {
            get {
                return ResourceManager.GetString("Placeholder_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Required).
        /// </summary>
        public static string Placeholder_Required {
            get {
                return ResourceManager.GetString("Placeholder_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Types_Audio {
            get {
                return ResourceManager.GetString("Types_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Types_Convert {
            get {
                return ResourceManager.GetString("Types_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Types_Custom {
            get {
                return ResourceManager.GetString("Types_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Types_Video {
            get {
                return ResourceManager.GetString("Types_Video", resourceCulture);
            }
        }
    }
}
