//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DLStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DLStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLControls.DLStrings", typeof(DLStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/akira.jpg.
        /// </summary>
        public static string AkiraImage {
            get {
                return ResourceManager.GetString("AkiraImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/Icon.ico.
        /// </summary>
        public static string AppIcon {
            get {
                return ResourceManager.GetString("AppIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/asutorufo.jpg.
        /// </summary>
        public static string AstolfoImage {
            get {
                return ResourceManager.GetString("AstolfoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/ButtonIcons/download.png.
        /// </summary>
        public static string DownloadIcon {
            get {
                return ResourceManager.GetString("DownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/ButtonIcons/file format.png.
        /// </summary>
        public static string FileFormatIcon {
            get {
                return ResourceManager.GetString("FileFormatIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/hime.jpg.
        /// </summary>
        public static string HimeImage {
            get {
                return ResourceManager.GetString("HimeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/megumin.jpg.
        /// </summary>
        public static string MeguminImage {
            get {
                return ResourceManager.GetString("MeguminImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/ButtonIcons/metadata.png.
        /// </summary>
        public static string MetadataIcon {
            get {
                return ResourceManager.GetString("MetadataIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/ButtonIcons/open file.png.
        /// </summary>
        public static string OpenFileIcon {
            get {
                return ResourceManager.GetString("OpenFileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/ButtonIcons/update.png.
        /// </summary>
        public static string UpdateIcon {
            get {
                return ResourceManager.GetString("UpdateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guicomp;component/Images/venti.jpg.
        /// </summary>
        public static string VentiImage {
            get {
                return ResourceManager.GetString("VentiImage", resourceCulture);
            }
        }
    }
}
